/* @imagine-readonly Generated by cloud schema sync. Do not edit manually. */

import { type Models } from 'node-appwrite'

export type FarmersCreate = {
  createdBy: string
  name: string
  phone: string
  mpesaNumber?: string | null
  groupId?: string | null
  role?: string
  trustScore?: number
  seasonsActive?: number
}

export type Farmers = Models.Row & {
  createdBy: string
  name: string
  phone: string
  mpesaNumber?: string | null
  groupId?: string | null
  role?: string
  trustScore?: number
  seasonsActive?: number
}

export type GroupsCreate = {
  createdBy: string
  name: string
  region?: string | null
  crop?: string | null
  leaderId?: string | null
  status?: string
  repaymentRate?: number
}

export type Groups = Models.Row & {
  createdBy: string
  name: string
  region?: string | null
  crop?: string | null
  leaderId?: string | null
  status?: string
  repaymentRate?: number
}

export type TransactionsCreate = {
  createdBy: string
  farmerId: string
  loanId: string
  mpesaReceiptNumber?: string | null
  amount: number
  type: string
  timestamp?: string | null
  callbackPayload?: string | null
}

export type Transactions = Models.Row & {
  createdBy: string
  farmerId: string
  loanId: string
  mpesaReceiptNumber?: string | null
  amount: number
  type: string
  timestamp?: string | null
  callbackPayload?: string | null
}

export type LoansCreate = {
  createdBy: string
  farmerId: string
  groupId: string
  amount: number
  season?: string | null
  disbursedAt?: string | null
  dueDate?: string | null
  status?: string
}

export type Loans = Models.Row & {
  createdBy: string
  farmerId: string
  groupId: string
  amount: number
  season?: string | null
  disbursedAt?: string | null
  dueDate?: string | null
  status?: string
}

export type InvestorsCreate = {
  createdBy: string
  name: string
  email: string
  type?: string
  capitalDeployed?: number
  targetYield?: number
  groupIds?: string[] | null
}

export type Investors = Models.Row & {
  createdBy: string
  name: string
  email: string
  type?: string
  capitalDeployed?: number
  targetYield?: number
  groupIds?: string[] | null
}

declare const __roleStringBrand: unique symbol
export type RoleString = string & { readonly [__roleStringBrand]: never }

export type RoleBuilder = {
  any: () => RoleString
  user: (userId: string, status?: string) => RoleString
  users: (status?: string) => RoleString
  guests: () => RoleString
  team: (teamId: string, role?: string) => RoleString
  member: (memberId: string) => RoleString
  label: (label: string) => RoleString
}

export type PermissionBuilder = {
  read: (role: RoleString) => string
  write: (role: RoleString) => string
  create: (role: RoleString) => string
  update: (role: RoleString) => string
  delete: (role: RoleString) => string
}

export type PermissionCallback = (
  permission: PermissionBuilder,
  role: RoleBuilder,
) => string[]

export type QueryValue = string | number | boolean

export type ExtractQueryValue<T> = T extends (infer U)[]
  ? U extends QueryValue
    ? U
    : never
  : T extends QueryValue | null
    ? NonNullable<T>
    : never

export type QueryableKeys<T> = keyof T

export type QueryBuilder<T> = {
  equal: <K extends QueryableKeys<T>>(
    field: K,
    value: ExtractQueryValue<T[K]>,
  ) => string
  notEqual: <K extends QueryableKeys<T>>(
    field: K,
    value: ExtractQueryValue<T[K]>,
  ) => string
  lessThan: <K extends QueryableKeys<T>>(
    field: K,
    value: ExtractQueryValue<T[K]>,
  ) => string
  lessThanEqual: <K extends QueryableKeys<T>>(
    field: K,
    value: ExtractQueryValue<T[K]>,
  ) => string
  greaterThan: <K extends QueryableKeys<T>>(
    field: K,
    value: ExtractQueryValue<T[K]>,
  ) => string
  greaterThanEqual: <K extends QueryableKeys<T>>(
    field: K,
    value: ExtractQueryValue<T[K]>,
  ) => string
  contains: <K extends QueryableKeys<T>>(
    field: K,
    value: ExtractQueryValue<T[K]>,
  ) => string
  search: <K extends QueryableKeys<T>>(field: K, value: string) => string
  isNull: <K extends QueryableKeys<T>>(field: K) => string
  isNotNull: <K extends QueryableKeys<T>>(field: K) => string
  startsWith: <K extends QueryableKeys<T>>(field: K, value: string) => string
  endsWith: <K extends QueryableKeys<T>>(field: K, value: string) => string
  between: <K extends QueryableKeys<T>>(
    field: K,
    start: ExtractQueryValue<T[K]>,
    end: ExtractQueryValue<T[K]>,
  ) => string
  select: <K extends keyof T>(fields: K[]) => string
  orderAsc: <K extends keyof T>(field: K) => string
  orderDesc: <K extends keyof T>(field: K) => string
  limit: (value: number) => string
  offset: (value: number) => string
  cursorAfter: (documentId: string) => string
  cursorBefore: (documentId: string) => string
  or: (...queries: string[]) => string
  and: (...queries: string[]) => string
}

export type DatabaseId = 'imagine-project-db'

export type DatabaseTableMap = {
  'imagine-project-db': {
    farmers: {
      create: (
        data: {
          createdBy: string
          name: string
          phone: string
          mpesaNumber?: string | null
          groupId?: string | null
          role?: string
          trustScore?: number
          seasonsActive?: number
        },
        options?: {
          rowId?: string
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Farmers>
      get: (id: string) => Promise<Farmers>
      update: (
        id: string,
        data: Partial<{
          createdBy: string
          name: string
          phone: string
          mpesaNumber?: string | null
          groupId?: string | null
          role?: string
          trustScore?: number
          seasonsActive?: number
        }>,
        options?: {
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Farmers>
      delete: (
        id: string,
        options?: { transactionId?: string },
      ) => Promise<void>
      list: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          contains: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          search: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Farmers>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Farmers>>(field: K) => string
          startsWith: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Farmers>>(
            field: K,
            start: ExtractQueryValue<Farmers[K]>,
            end: ExtractQueryValue<Farmers[K]>,
          ) => string
          select: <K extends keyof Farmers>(fields: K[]) => string
          orderAsc: <K extends keyof Farmers>(field: K) => string
          orderDesc: <K extends keyof Farmers>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
      }) => Promise<{ total: number; rows: Farmers[] }>
      createMany: (
        rows: Array<
          {
            createdBy: string
            name: string
            phone: string
            mpesaNumber?: string | null
            groupId?: string | null
            role?: string
            trustScore?: number
            seasonsActive?: number
          } & { $id?: string; $permissions?: string[] }
        >,
        options?: { transactionId?: string },
      ) => Promise<{ total: number; rows: Farmers[] }>
      updateMany: (
        data: Partial<{
          createdBy: string
          name: string
          phone: string
          mpesaNumber?: string | null
          groupId?: string | null
          role?: string
          trustScore?: number
          seasonsActive?: number
        }>,
        options?: {
          queries?: (q: {
            equal: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: ExtractQueryValue<Farmers[K]>,
            ) => string
            notEqual: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: ExtractQueryValue<Farmers[K]>,
            ) => string
            lessThan: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: ExtractQueryValue<Farmers[K]>,
            ) => string
            lessThanEqual: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: ExtractQueryValue<Farmers[K]>,
            ) => string
            greaterThan: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: ExtractQueryValue<Farmers[K]>,
            ) => string
            greaterThanEqual: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: ExtractQueryValue<Farmers[K]>,
            ) => string
            contains: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: ExtractQueryValue<Farmers[K]>,
            ) => string
            search: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: string,
            ) => string
            isNull: <K extends QueryableKeys<Farmers>>(field: K) => string
            isNotNull: <K extends QueryableKeys<Farmers>>(field: K) => string
            startsWith: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: string,
            ) => string
            endsWith: <K extends QueryableKeys<Farmers>>(
              field: K,
              value: string,
            ) => string
            between: <K extends QueryableKeys<Farmers>>(
              field: K,
              start: ExtractQueryValue<Farmers[K]>,
              end: ExtractQueryValue<Farmers[K]>,
            ) => string
            select: <K extends keyof Farmers>(fields: K[]) => string
            orderAsc: <K extends keyof Farmers>(field: K) => string
            orderDesc: <K extends keyof Farmers>(field: K) => string
            limit: (value: number) => string
            offset: (value: number) => string
            cursorAfter: (documentId: string) => string
            cursorBefore: (documentId: string) => string
            or: (...queries: string[]) => string
            and: (...queries: string[]) => string
          }) => string[]
          transactionId?: string
        },
      ) => Promise<{ total: number; rows: Farmers[] }>
      deleteMany: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          contains: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: ExtractQueryValue<Farmers[K]>,
          ) => string
          search: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Farmers>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Farmers>>(field: K) => string
          startsWith: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Farmers>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Farmers>>(
            field: K,
            start: ExtractQueryValue<Farmers[K]>,
            end: ExtractQueryValue<Farmers[K]>,
          ) => string
          select: <K extends keyof Farmers>(fields: K[]) => string
          orderAsc: <K extends keyof Farmers>(field: K) => string
          orderDesc: <K extends keyof Farmers>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
        transactionId?: string
      }) => Promise<{ total: number; rows: Farmers[] }>
    }
    groups: {
      create: (
        data: {
          createdBy: string
          name: string
          region?: string | null
          crop?: string | null
          leaderId?: string | null
          status?: string
          repaymentRate?: number
        },
        options?: {
          rowId?: string
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Groups>
      get: (id: string) => Promise<Groups>
      update: (
        id: string,
        data: Partial<{
          createdBy: string
          name: string
          region?: string | null
          crop?: string | null
          leaderId?: string | null
          status?: string
          repaymentRate?: number
        }>,
        options?: {
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Groups>
      delete: (
        id: string,
        options?: { transactionId?: string },
      ) => Promise<void>
      list: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          contains: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          search: <K extends QueryableKeys<Groups>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Groups>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Groups>>(field: K) => string
          startsWith: <K extends QueryableKeys<Groups>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Groups>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Groups>>(
            field: K,
            start: ExtractQueryValue<Groups[K]>,
            end: ExtractQueryValue<Groups[K]>,
          ) => string
          select: <K extends keyof Groups>(fields: K[]) => string
          orderAsc: <K extends keyof Groups>(field: K) => string
          orderDesc: <K extends keyof Groups>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
      }) => Promise<{ total: number; rows: Groups[] }>
      createMany: (
        rows: Array<
          {
            createdBy: string
            name: string
            region?: string | null
            crop?: string | null
            leaderId?: string | null
            status?: string
            repaymentRate?: number
          } & { $id?: string; $permissions?: string[] }
        >,
        options?: { transactionId?: string },
      ) => Promise<{ total: number; rows: Groups[] }>
      updateMany: (
        data: Partial<{
          createdBy: string
          name: string
          region?: string | null
          crop?: string | null
          leaderId?: string | null
          status?: string
          repaymentRate?: number
        }>,
        options?: {
          queries?: (q: {
            equal: <K extends QueryableKeys<Groups>>(
              field: K,
              value: ExtractQueryValue<Groups[K]>,
            ) => string
            notEqual: <K extends QueryableKeys<Groups>>(
              field: K,
              value: ExtractQueryValue<Groups[K]>,
            ) => string
            lessThan: <K extends QueryableKeys<Groups>>(
              field: K,
              value: ExtractQueryValue<Groups[K]>,
            ) => string
            lessThanEqual: <K extends QueryableKeys<Groups>>(
              field: K,
              value: ExtractQueryValue<Groups[K]>,
            ) => string
            greaterThan: <K extends QueryableKeys<Groups>>(
              field: K,
              value: ExtractQueryValue<Groups[K]>,
            ) => string
            greaterThanEqual: <K extends QueryableKeys<Groups>>(
              field: K,
              value: ExtractQueryValue<Groups[K]>,
            ) => string
            contains: <K extends QueryableKeys<Groups>>(
              field: K,
              value: ExtractQueryValue<Groups[K]>,
            ) => string
            search: <K extends QueryableKeys<Groups>>(
              field: K,
              value: string,
            ) => string
            isNull: <K extends QueryableKeys<Groups>>(field: K) => string
            isNotNull: <K extends QueryableKeys<Groups>>(field: K) => string
            startsWith: <K extends QueryableKeys<Groups>>(
              field: K,
              value: string,
            ) => string
            endsWith: <K extends QueryableKeys<Groups>>(
              field: K,
              value: string,
            ) => string
            between: <K extends QueryableKeys<Groups>>(
              field: K,
              start: ExtractQueryValue<Groups[K]>,
              end: ExtractQueryValue<Groups[K]>,
            ) => string
            select: <K extends keyof Groups>(fields: K[]) => string
            orderAsc: <K extends keyof Groups>(field: K) => string
            orderDesc: <K extends keyof Groups>(field: K) => string
            limit: (value: number) => string
            offset: (value: number) => string
            cursorAfter: (documentId: string) => string
            cursorBefore: (documentId: string) => string
            or: (...queries: string[]) => string
            and: (...queries: string[]) => string
          }) => string[]
          transactionId?: string
        },
      ) => Promise<{ total: number; rows: Groups[] }>
      deleteMany: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          contains: <K extends QueryableKeys<Groups>>(
            field: K,
            value: ExtractQueryValue<Groups[K]>,
          ) => string
          search: <K extends QueryableKeys<Groups>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Groups>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Groups>>(field: K) => string
          startsWith: <K extends QueryableKeys<Groups>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Groups>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Groups>>(
            field: K,
            start: ExtractQueryValue<Groups[K]>,
            end: ExtractQueryValue<Groups[K]>,
          ) => string
          select: <K extends keyof Groups>(fields: K[]) => string
          orderAsc: <K extends keyof Groups>(field: K) => string
          orderDesc: <K extends keyof Groups>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
        transactionId?: string
      }) => Promise<{ total: number; rows: Groups[] }>
    }
    transactions: {
      create: (
        data: {
          createdBy: string
          farmerId: string
          loanId: string
          mpesaReceiptNumber?: string | null
          amount: number
          type: string
          timestamp?: string | null
          callbackPayload?: string | null
        },
        options?: {
          rowId?: string
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Transactions>
      get: (id: string) => Promise<Transactions>
      update: (
        id: string,
        data: Partial<{
          createdBy: string
          farmerId: string
          loanId: string
          mpesaReceiptNumber?: string | null
          amount: number
          type: string
          timestamp?: string | null
          callbackPayload?: string | null
        }>,
        options?: {
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Transactions>
      delete: (
        id: string,
        options?: { transactionId?: string },
      ) => Promise<void>
      list: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          contains: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          search: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Transactions>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Transactions>>(field: K) => string
          startsWith: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Transactions>>(
            field: K,
            start: ExtractQueryValue<Transactions[K]>,
            end: ExtractQueryValue<Transactions[K]>,
          ) => string
          select: <K extends keyof Transactions>(fields: K[]) => string
          orderAsc: <K extends keyof Transactions>(field: K) => string
          orderDesc: <K extends keyof Transactions>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
      }) => Promise<{ total: number; rows: Transactions[] }>
      createMany: (
        rows: Array<
          {
            createdBy: string
            farmerId: string
            loanId: string
            mpesaReceiptNumber?: string | null
            amount: number
            type: string
            timestamp?: string | null
            callbackPayload?: string | null
          } & { $id?: string; $permissions?: string[] }
        >,
        options?: { transactionId?: string },
      ) => Promise<{ total: number; rows: Transactions[] }>
      updateMany: (
        data: Partial<{
          createdBy: string
          farmerId: string
          loanId: string
          mpesaReceiptNumber?: string | null
          amount: number
          type: string
          timestamp?: string | null
          callbackPayload?: string | null
        }>,
        options?: {
          queries?: (q: {
            equal: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: ExtractQueryValue<Transactions[K]>,
            ) => string
            notEqual: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: ExtractQueryValue<Transactions[K]>,
            ) => string
            lessThan: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: ExtractQueryValue<Transactions[K]>,
            ) => string
            lessThanEqual: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: ExtractQueryValue<Transactions[K]>,
            ) => string
            greaterThan: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: ExtractQueryValue<Transactions[K]>,
            ) => string
            greaterThanEqual: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: ExtractQueryValue<Transactions[K]>,
            ) => string
            contains: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: ExtractQueryValue<Transactions[K]>,
            ) => string
            search: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: string,
            ) => string
            isNull: <K extends QueryableKeys<Transactions>>(field: K) => string
            isNotNull: <K extends QueryableKeys<Transactions>>(
              field: K,
            ) => string
            startsWith: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: string,
            ) => string
            endsWith: <K extends QueryableKeys<Transactions>>(
              field: K,
              value: string,
            ) => string
            between: <K extends QueryableKeys<Transactions>>(
              field: K,
              start: ExtractQueryValue<Transactions[K]>,
              end: ExtractQueryValue<Transactions[K]>,
            ) => string
            select: <K extends keyof Transactions>(fields: K[]) => string
            orderAsc: <K extends keyof Transactions>(field: K) => string
            orderDesc: <K extends keyof Transactions>(field: K) => string
            limit: (value: number) => string
            offset: (value: number) => string
            cursorAfter: (documentId: string) => string
            cursorBefore: (documentId: string) => string
            or: (...queries: string[]) => string
            and: (...queries: string[]) => string
          }) => string[]
          transactionId?: string
        },
      ) => Promise<{ total: number; rows: Transactions[] }>
      deleteMany: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          contains: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: ExtractQueryValue<Transactions[K]>,
          ) => string
          search: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Transactions>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Transactions>>(field: K) => string
          startsWith: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Transactions>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Transactions>>(
            field: K,
            start: ExtractQueryValue<Transactions[K]>,
            end: ExtractQueryValue<Transactions[K]>,
          ) => string
          select: <K extends keyof Transactions>(fields: K[]) => string
          orderAsc: <K extends keyof Transactions>(field: K) => string
          orderDesc: <K extends keyof Transactions>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
        transactionId?: string
      }) => Promise<{ total: number; rows: Transactions[] }>
    }
    loans: {
      create: (
        data: {
          createdBy: string
          farmerId: string
          groupId: string
          amount: number
          season?: string | null
          disbursedAt?: string | null
          dueDate?: string | null
          status?: string
        },
        options?: {
          rowId?: string
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Loans>
      get: (id: string) => Promise<Loans>
      update: (
        id: string,
        data: Partial<{
          createdBy: string
          farmerId: string
          groupId: string
          amount: number
          season?: string | null
          disbursedAt?: string | null
          dueDate?: string | null
          status?: string
        }>,
        options?: {
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Loans>
      delete: (
        id: string,
        options?: { transactionId?: string },
      ) => Promise<void>
      list: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          contains: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          search: <K extends QueryableKeys<Loans>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Loans>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Loans>>(field: K) => string
          startsWith: <K extends QueryableKeys<Loans>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Loans>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Loans>>(
            field: K,
            start: ExtractQueryValue<Loans[K]>,
            end: ExtractQueryValue<Loans[K]>,
          ) => string
          select: <K extends keyof Loans>(fields: K[]) => string
          orderAsc: <K extends keyof Loans>(field: K) => string
          orderDesc: <K extends keyof Loans>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
      }) => Promise<{ total: number; rows: Loans[] }>
      createMany: (
        rows: Array<
          {
            createdBy: string
            farmerId: string
            groupId: string
            amount: number
            season?: string | null
            disbursedAt?: string | null
            dueDate?: string | null
            status?: string
          } & { $id?: string; $permissions?: string[] }
        >,
        options?: { transactionId?: string },
      ) => Promise<{ total: number; rows: Loans[] }>
      updateMany: (
        data: Partial<{
          createdBy: string
          farmerId: string
          groupId: string
          amount: number
          season?: string | null
          disbursedAt?: string | null
          dueDate?: string | null
          status?: string
        }>,
        options?: {
          queries?: (q: {
            equal: <K extends QueryableKeys<Loans>>(
              field: K,
              value: ExtractQueryValue<Loans[K]>,
            ) => string
            notEqual: <K extends QueryableKeys<Loans>>(
              field: K,
              value: ExtractQueryValue<Loans[K]>,
            ) => string
            lessThan: <K extends QueryableKeys<Loans>>(
              field: K,
              value: ExtractQueryValue<Loans[K]>,
            ) => string
            lessThanEqual: <K extends QueryableKeys<Loans>>(
              field: K,
              value: ExtractQueryValue<Loans[K]>,
            ) => string
            greaterThan: <K extends QueryableKeys<Loans>>(
              field: K,
              value: ExtractQueryValue<Loans[K]>,
            ) => string
            greaterThanEqual: <K extends QueryableKeys<Loans>>(
              field: K,
              value: ExtractQueryValue<Loans[K]>,
            ) => string
            contains: <K extends QueryableKeys<Loans>>(
              field: K,
              value: ExtractQueryValue<Loans[K]>,
            ) => string
            search: <K extends QueryableKeys<Loans>>(
              field: K,
              value: string,
            ) => string
            isNull: <K extends QueryableKeys<Loans>>(field: K) => string
            isNotNull: <K extends QueryableKeys<Loans>>(field: K) => string
            startsWith: <K extends QueryableKeys<Loans>>(
              field: K,
              value: string,
            ) => string
            endsWith: <K extends QueryableKeys<Loans>>(
              field: K,
              value: string,
            ) => string
            between: <K extends QueryableKeys<Loans>>(
              field: K,
              start: ExtractQueryValue<Loans[K]>,
              end: ExtractQueryValue<Loans[K]>,
            ) => string
            select: <K extends keyof Loans>(fields: K[]) => string
            orderAsc: <K extends keyof Loans>(field: K) => string
            orderDesc: <K extends keyof Loans>(field: K) => string
            limit: (value: number) => string
            offset: (value: number) => string
            cursorAfter: (documentId: string) => string
            cursorBefore: (documentId: string) => string
            or: (...queries: string[]) => string
            and: (...queries: string[]) => string
          }) => string[]
          transactionId?: string
        },
      ) => Promise<{ total: number; rows: Loans[] }>
      deleteMany: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          contains: <K extends QueryableKeys<Loans>>(
            field: K,
            value: ExtractQueryValue<Loans[K]>,
          ) => string
          search: <K extends QueryableKeys<Loans>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Loans>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Loans>>(field: K) => string
          startsWith: <K extends QueryableKeys<Loans>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Loans>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Loans>>(
            field: K,
            start: ExtractQueryValue<Loans[K]>,
            end: ExtractQueryValue<Loans[K]>,
          ) => string
          select: <K extends keyof Loans>(fields: K[]) => string
          orderAsc: <K extends keyof Loans>(field: K) => string
          orderDesc: <K extends keyof Loans>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
        transactionId?: string
      }) => Promise<{ total: number; rows: Loans[] }>
    }
    investors: {
      create: (
        data: {
          createdBy: string
          name: string
          email: string
          type?: string
          capitalDeployed?: number
          targetYield?: number
          groupIds?: string[] | null
        },
        options?: {
          rowId?: string
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Investors>
      get: (id: string) => Promise<Investors>
      update: (
        id: string,
        data: Partial<{
          createdBy: string
          name: string
          email: string
          type?: string
          capitalDeployed?: number
          targetYield?: number
          groupIds?: string[] | null
        }>,
        options?: {
          permissions?: (
            permission: {
              read: (role: RoleString) => string
              write: (role: RoleString) => string
              create: (role: RoleString) => string
              update: (role: RoleString) => string
              delete: (role: RoleString) => string
            },
            role: {
              any: () => RoleString
              user: (userId: string, status?: string) => RoleString
              users: (status?: string) => RoleString
              guests: () => RoleString
              team: (teamId: string, role?: string) => RoleString
              member: (memberId: string) => RoleString
              label: (label: string) => RoleString
            },
          ) => string[]
          transactionId?: string
        },
      ) => Promise<Investors>
      delete: (
        id: string,
        options?: { transactionId?: string },
      ) => Promise<void>
      list: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          contains: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          search: <K extends QueryableKeys<Investors>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Investors>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Investors>>(field: K) => string
          startsWith: <K extends QueryableKeys<Investors>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Investors>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Investors>>(
            field: K,
            start: ExtractQueryValue<Investors[K]>,
            end: ExtractQueryValue<Investors[K]>,
          ) => string
          select: <K extends keyof Investors>(fields: K[]) => string
          orderAsc: <K extends keyof Investors>(field: K) => string
          orderDesc: <K extends keyof Investors>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
      }) => Promise<{ total: number; rows: Investors[] }>
      createMany: (
        rows: Array<
          {
            createdBy: string
            name: string
            email: string
            type?: string
            capitalDeployed?: number
            targetYield?: number
            groupIds?: string[] | null
          } & { $id?: string; $permissions?: string[] }
        >,
        options?: { transactionId?: string },
      ) => Promise<{ total: number; rows: Investors[] }>
      updateMany: (
        data: Partial<{
          createdBy: string
          name: string
          email: string
          type?: string
          capitalDeployed?: number
          targetYield?: number
          groupIds?: string[] | null
        }>,
        options?: {
          queries?: (q: {
            equal: <K extends QueryableKeys<Investors>>(
              field: K,
              value: ExtractQueryValue<Investors[K]>,
            ) => string
            notEqual: <K extends QueryableKeys<Investors>>(
              field: K,
              value: ExtractQueryValue<Investors[K]>,
            ) => string
            lessThan: <K extends QueryableKeys<Investors>>(
              field: K,
              value: ExtractQueryValue<Investors[K]>,
            ) => string
            lessThanEqual: <K extends QueryableKeys<Investors>>(
              field: K,
              value: ExtractQueryValue<Investors[K]>,
            ) => string
            greaterThan: <K extends QueryableKeys<Investors>>(
              field: K,
              value: ExtractQueryValue<Investors[K]>,
            ) => string
            greaterThanEqual: <K extends QueryableKeys<Investors>>(
              field: K,
              value: ExtractQueryValue<Investors[K]>,
            ) => string
            contains: <K extends QueryableKeys<Investors>>(
              field: K,
              value: ExtractQueryValue<Investors[K]>,
            ) => string
            search: <K extends QueryableKeys<Investors>>(
              field: K,
              value: string,
            ) => string
            isNull: <K extends QueryableKeys<Investors>>(field: K) => string
            isNotNull: <K extends QueryableKeys<Investors>>(field: K) => string
            startsWith: <K extends QueryableKeys<Investors>>(
              field: K,
              value: string,
            ) => string
            endsWith: <K extends QueryableKeys<Investors>>(
              field: K,
              value: string,
            ) => string
            between: <K extends QueryableKeys<Investors>>(
              field: K,
              start: ExtractQueryValue<Investors[K]>,
              end: ExtractQueryValue<Investors[K]>,
            ) => string
            select: <K extends keyof Investors>(fields: K[]) => string
            orderAsc: <K extends keyof Investors>(field: K) => string
            orderDesc: <K extends keyof Investors>(field: K) => string
            limit: (value: number) => string
            offset: (value: number) => string
            cursorAfter: (documentId: string) => string
            cursorBefore: (documentId: string) => string
            or: (...queries: string[]) => string
            and: (...queries: string[]) => string
          }) => string[]
          transactionId?: string
        },
      ) => Promise<{ total: number; rows: Investors[] }>
      deleteMany: (options?: {
        queries?: (q: {
          equal: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          notEqual: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          lessThan: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          lessThanEqual: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          greaterThan: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          greaterThanEqual: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          contains: <K extends QueryableKeys<Investors>>(
            field: K,
            value: ExtractQueryValue<Investors[K]>,
          ) => string
          search: <K extends QueryableKeys<Investors>>(
            field: K,
            value: string,
          ) => string
          isNull: <K extends QueryableKeys<Investors>>(field: K) => string
          isNotNull: <K extends QueryableKeys<Investors>>(field: K) => string
          startsWith: <K extends QueryableKeys<Investors>>(
            field: K,
            value: string,
          ) => string
          endsWith: <K extends QueryableKeys<Investors>>(
            field: K,
            value: string,
          ) => string
          between: <K extends QueryableKeys<Investors>>(
            field: K,
            start: ExtractQueryValue<Investors[K]>,
            end: ExtractQueryValue<Investors[K]>,
          ) => string
          select: <K extends keyof Investors>(fields: K[]) => string
          orderAsc: <K extends keyof Investors>(field: K) => string
          orderDesc: <K extends keyof Investors>(field: K) => string
          limit: (value: number) => string
          offset: (value: number) => string
          cursorAfter: (documentId: string) => string
          cursorBefore: (documentId: string) => string
          or: (...queries: string[]) => string
          and: (...queries: string[]) => string
        }) => string[]
        transactionId?: string
      }) => Promise<{ total: number; rows: Investors[] }>
    }
  }
}

export type DatabaseHandle<D extends DatabaseId> = {
  use: <T extends keyof DatabaseTableMap[D] & string>(
    tableId: T,
  ) => DatabaseTableMap[D][T]
  create: (
    tableId: string,
    name: string,
    options?: {
      permissions?: (
        permission: {
          read: (role: RoleString) => string
          write: (role: RoleString) => string
          create: (role: RoleString) => string
          update: (role: RoleString) => string
          delete: (role: RoleString) => string
        },
        role: {
          any: () => RoleString
          user: (userId: string, status?: string) => RoleString
          users: (status?: string) => RoleString
          guests: () => RoleString
          team: (teamId: string, role?: string) => RoleString
          member: (memberId: string) => RoleString
          label: (label: string) => RoleString
        },
      ) => string[]
      rowSecurity?: boolean
      enabled?: boolean
      columns?: object[]
      indexes?: object[]
    },
  ) => Promise<Models.Table>
  update: <T extends keyof DatabaseTableMap[D] & string>(
    tableId: T,
    options?: {
      name?: string
      permissions?: (
        permission: {
          read: (role: RoleString) => string
          write: (role: RoleString) => string
          create: (role: RoleString) => string
          update: (role: RoleString) => string
          delete: (role: RoleString) => string
        },
        role: {
          any: () => RoleString
          user: (userId: string, status?: string) => RoleString
          users: (status?: string) => RoleString
          guests: () => RoleString
          team: (teamId: string, role?: string) => RoleString
          member: (memberId: string) => RoleString
          label: (label: string) => RoleString
        },
      ) => string[]
      rowSecurity?: boolean
      enabled?: boolean
    },
  ) => Promise<Models.Table>
  delete: <T extends keyof DatabaseTableMap[D] & string>(
    tableId: T,
  ) => Promise<void>
}

export type DatabaseTables = {
  use: <D extends DatabaseId>(databaseId: D) => DatabaseHandle<D>
  create: (
    databaseId: string,
    name: string,
    options?: { enabled?: boolean },
  ) => Promise<Models.Database>
  update: <D extends DatabaseId>(
    databaseId: D,
    options?: { name?: string; enabled?: boolean },
  ) => Promise<Models.Database>
  delete: <D extends DatabaseId>(databaseId: D) => Promise<void>
}
