/* @imagine-readonly Generated by cloud schema sync. Do not edit manually. */

import {
  Client,
  TablesDB,
  ID,
  Query,
  type Models,
  Permission,
  Role,
} from 'node-appwrite'
import type {
  DatabaseHandle,
  DatabaseId,
  DatabaseTableMap,
  DatabaseTables,
  QueryBuilder,
  PermissionBuilder,
  RoleBuilder,
  RoleString,
} from './appwrite.types'
import { PROJECT_ID, ENDPOINT, API_KEY } from './constants.js'

const createQueryBuilder = (): any => ({
  equal: (field: any, value: any) => Query.equal(String(field), value),
  notEqual: (field: any, value: any) => Query.notEqual(String(field), value),
  lessThan: (field: any, value: any) => Query.lessThan(String(field), value),
  lessThanEqual: (field: any, value: any) => Query.lessThanEqual(String(field), value),
  greaterThan: (field: any, value: any) => Query.greaterThan(String(field), value),
  greaterThanEqual: (field: any, value: any) => Query.greaterThanEqual(String(field), value),
  contains: (field: any, value: any) => Query.contains(String(field), value),
  search: (field: any, value: any) => Query.search(String(field), value),
  isNull: (field: any) => Query.isNull(String(field)),
  isNotNull: (field: any) => Query.isNotNull(String(field)),
  startsWith: (field: any, value: any) => Query.startsWith(String(field), value),
  endsWith: (field: any, value: any) => Query.endsWith(String(field), value),
  between: (field: any, start: any, end: any) => Query.between(String(field), start, end),
  select: (fields: any) => Query.select(fields),
  orderAsc: (field: any) => Query.orderAsc(String(field)),
  orderDesc: (field: any) => Query.orderDesc(String(field)),
  limit: (value: any) => Query.limit(value),
  offset: (value: any) => Query.offset(value),
  cursorAfter: (documentId: any) => Query.cursorAfter(documentId),
  cursorBefore: (documentId: any) => Query.cursorBefore(documentId),
  or: (...queries: any[]) => Query.or(queries),
  and: (...queries: any[]) => Query.and(queries),
})

const tableIdMap: Record<string, Record<string, string>> = Object.create(null)
tableIdMap['imagine-project-db'] = Object.create(null)
tableIdMap['imagine-project-db']['farmers'] = 'farmers'
tableIdMap['imagine-project-db']['groups'] = 'groups'
tableIdMap['imagine-project-db']['transactions'] = 'transactions'
tableIdMap['imagine-project-db']['loans'] = 'loans'
tableIdMap['imagine-project-db']['investors'] = 'investors'

const tablesWithRelationships = new Set<string>()

const roleBuilder: RoleBuilder = {
  any: () => Role.any() as RoleString,
  user: (userId: string, status?: string) => Role.user(userId, status) as RoleString,
  users: (status?: string) => Role.users(status) as RoleString,
  guests: () => Role.guests() as RoleString,
  team: (teamId: string, role?: string) => Role.team(teamId, role) as RoleString,
  member: (memberId: string) => Role.member(memberId) as RoleString,
  label: (label: string) => Role.label(label) as RoleString,
}

const permissionBuilder: PermissionBuilder = {
  read: (role: RoleString) => Permission.read(role),
  write: (role: RoleString) => Permission.write(role),
  create: (role: RoleString) => Permission.create(role),
  update: (role: RoleString) => Permission.update(role),
  delete: (role: RoleString) => Permission.delete(role),
}

const resolvePermissions = (
  callback?: (
    permission: {
      read: (role: RoleString) => string
      write: (role: RoleString) => string
      create: (role: RoleString) => string
      update: (role: RoleString) => string
      delete: (role: RoleString) => string
    },
    role: {
      any: () => RoleString
      user: (userId: string, status?: string) => RoleString
      users: (status?: string) => RoleString
      guests: () => RoleString
      team: (teamId: string, role?: string) => RoleString
      member: (memberId: string) => RoleString
      label: (label: string) => RoleString
    },
  ) => string[],
): string[] | undefined => callback?.(permissionBuilder, roleBuilder)

function createTableApi<T extends Models.Row>(
  tablesDB: TablesDB,
  databaseId: string,
  tableId: string,
) {
  return {
    create: (
      data: Omit<T, keyof Models.Row>,
      options?: {
        rowId?: string
        permissions?: (
          permission: {
            read: (role: RoleString) => string
            write: (role: RoleString) => string
            create: (role: RoleString) => string
            update: (role: RoleString) => string
            delete: (role: RoleString) => string
          },
          role: {
            any: () => RoleString
            user: (userId: string, status?: string) => RoleString
            users: (status?: string) => RoleString
            guests: () => RoleString
            team: (teamId: string, role?: string) => RoleString
            member: (memberId: string) => RoleString
            label: (label: string) => RoleString
          },
        ) => string[]
        transactionId?: string
      },
    ) =>
      tablesDB.createRow<T>({
        databaseId,
        tableId,
        rowId: options?.rowId ?? ID.unique(),
        data: data as T extends Models.DefaultRow
          ? Partial<Models.Row> & Record<string, unknown>
          : Partial<Models.Row> & Omit<T, keyof Models.Row>,
        permissions: resolvePermissions(options?.permissions),
        transactionId: options?.transactionId,
      }),
    get: (id: string) =>
      tablesDB.getRow<T>({
        databaseId,
        tableId,
        rowId: id,
      }),
    update: (
      id: string,
      data: Partial<Omit<T, keyof Models.Row>>,
      options?: {
        permissions?: (
          permission: {
            read: (role: RoleString) => string
            write: (role: RoleString) => string
            create: (role: RoleString) => string
            update: (role: RoleString) => string
            delete: (role: RoleString) => string
          },
          role: {
            any: () => RoleString
            user: (userId: string, status?: string) => RoleString
            users: (status?: string) => RoleString
            guests: () => RoleString
            team: (teamId: string, role?: string) => RoleString
            member: (memberId: string) => RoleString
            label: (label: string) => RoleString
          },
        ) => string[]
        transactionId?: string
      },
    ) =>
      tablesDB.updateRow<T>({
        databaseId,
        tableId,
        rowId: id,
        data: data as T extends Models.DefaultRow
          ? Partial<Models.Row> & Record<string, unknown>
          : Partial<Models.Row> & Partial<Omit<T, keyof Models.Row>>,
        ...(options?.permissions
          ? { permissions: resolvePermissions(options.permissions) }
          : {}),
        transactionId: options?.transactionId,
      }),
    delete: async (id: string, options?: { transactionId?: string }) => {
      await tablesDB.deleteRow({
        databaseId,
        tableId,
        rowId: id,
        transactionId: options?.transactionId,
      })
    },
    list: (options?: { queries?: (q: QueryBuilder<T>) => string[] }) =>
      tablesDB.listRows<T>({
        databaseId,
        tableId,
        queries: options?.queries?.(createQueryBuilder()),
      }),
    createMany: (rows: object[], options?: { transactionId?: string }) =>
      tablesDB.createRows({
        databaseId,
        tableId,
        rows,
        transactionId: options?.transactionId,
      }),
    updateMany: (
      data: object,
      options?: {
        queries?: (q: QueryBuilder<T>) => string[]
        transactionId?: string
      },
    ) =>
      tablesDB.updateRows({
        databaseId,
        tableId,
        data,
        queries: options?.queries?.(createQueryBuilder()),
        transactionId: options?.transactionId,
      }),
    deleteMany: (options?: {
      queries?: (q: QueryBuilder<T>) => string[]
      transactionId?: string
    }) =>
      tablesDB.deleteRows({
        databaseId,
        tableId,
        queries: options?.queries?.(createQueryBuilder()),
        transactionId: options?.transactionId,
      }),
  }
}

const hasBulkMethods = (dbId: string, tableId: string) =>
  !tablesWithRelationships.has(`${dbId}:${tableId}`)

const hasOwn = (obj: unknown, key: string): boolean =>
  obj != null && Object.prototype.hasOwnProperty.call(obj, key)

function createDatabaseHandle<D extends DatabaseId>(
  tablesDB: TablesDB,
  databaseId: D,
): DatabaseHandle<D> {
  const tableApiCache = new Map<string, unknown>()
  const dbMap = tableIdMap[databaseId]

  return {
    use: <T extends keyof DatabaseTableMap[D] & string>(
      tableId: T,
    ): DatabaseTableMap[D][T] => {
      if (!hasOwn(dbMap, tableId)) {
        throw new Error(
          `Unknown table "${tableId}" in database "${databaseId}"`,
        )
      }

      if (!tableApiCache.has(tableId)) {
        const resolvedTableId = dbMap[tableId]
        const api = createTableApi(tablesDB, databaseId, resolvedTableId)

        // Remove bulk methods for tables with relationships
        if (!hasBulkMethods(databaseId, tableId)) {
          delete (api as Record<string, unknown>).createMany
          delete (api as Record<string, unknown>).updateMany
          delete (api as Record<string, unknown>).deleteMany
        }
        tableApiCache.set(tableId, api)
      }
      return tableApiCache.get(tableId) as DatabaseTableMap[D][T]
    },
    create: (
      tableId: string,
      name: string,
      options?: {
        permissions?: (
          permission: {
            read: (role: RoleString) => string
            write: (role: RoleString) => string
            create: (role: RoleString) => string
            update: (role: RoleString) => string
            delete: (role: RoleString) => string
          },
          role: {
            any: () => RoleString
            user: (userId: string, status?: string) => RoleString
            users: (status?: string) => RoleString
            guests: () => RoleString
            team: (teamId: string, role?: string) => RoleString
            member: (memberId: string) => RoleString
            label: (label: string) => RoleString
          },
        ) => string[]
        rowSecurity?: boolean
        enabled?: boolean
        columns?: object[]
        indexes?: object[]
      },
    ) =>
      tablesDB.createTable({
        databaseId,
        tableId,
        name,
        permissions: resolvePermissions(options?.permissions),
        rowSecurity: options?.rowSecurity,
        enabled: options?.enabled,
        columns: options?.columns,
        indexes: options?.indexes,
      }),
    update: (
      tableId: string,
      options?: {
        name?: string
        permissions?: (
          permission: {
            read: (role: RoleString) => string
            write: (role: RoleString) => string
            create: (role: RoleString) => string
            update: (role: RoleString) => string
            delete: (role: RoleString) => string
          },
          role: {
            any: () => RoleString
            user: (userId: string, status?: string) => RoleString
            users: (status?: string) => RoleString
            guests: () => RoleString
            team: (teamId: string, role?: string) => RoleString
            member: (memberId: string) => RoleString
            label: (label: string) => RoleString
          },
        ) => string[]
        rowSecurity?: boolean
        enabled?: boolean
      },
    ) => {
      if (!hasOwn(dbMap, tableId)) {
        throw new Error(
          `Unknown table "${tableId}" in database "${databaseId}"`,
        )
      }
      const resolvedTableId = dbMap[tableId]
      const updateOpts: any = {
        databaseId,
        tableId: resolvedTableId,
        permissions: resolvePermissions(options?.permissions),
        rowSecurity: options?.rowSecurity,
        enabled: options?.enabled,
      }
      if (options?.name !== undefined) {
        updateOpts.name = options.name
      }
      return tablesDB.updateTable(updateOpts)
    },
    delete: async (tableId: string) => {
      if (!hasOwn(dbMap, tableId)) {
        throw new Error(
          `Unknown table "${tableId}" in database "${databaseId}"`,
        )
      }
      const resolvedTableId = dbMap[tableId]
      await tablesDB.deleteTable({
        databaseId,
        tableId: resolvedTableId,
      })
    },
  }
}

function createDatabasesApi(tablesDB: TablesDB): DatabaseTables {
  const dbCache = new Map<DatabaseId, ReturnType<typeof createDatabaseHandle>>()

  return {
    use: (databaseId: DatabaseId) => {
      if (!hasOwn(tableIdMap, databaseId)) {
        throw new Error(`Unknown database "${databaseId}"`)
      }

      if (!dbCache.has(databaseId)) {
        dbCache.set(databaseId, createDatabaseHandle(tablesDB, databaseId))
      }
      return dbCache.get(databaseId)
    },
    create: (
      databaseId: string,
      name: string,
      options?: { enabled?: boolean },
    ) =>
      tablesDB.create({
        databaseId,
        name,
        enabled: options?.enabled,
      }),
    update: (
      databaseId: DatabaseId,
      options?: { name?: string; enabled?: boolean },
    ) => {
      return tablesDB.update({
        databaseId,
        name: options?.name ?? databaseId,
        enabled: options?.enabled,
      })
    },
    delete: async (databaseId: DatabaseId) => {
      await tablesDB.delete({
        databaseId,
      })
    },
  } as DatabaseTables
}

// Initialize client
const client = new Client()
  .setEndpoint(ENDPOINT)
  .setProject(PROJECT_ID)
  .setKey(API_KEY)

const tablesDB = new TablesDB(client)

export const databases: DatabaseTables = createDatabasesApi(tablesDB)
